---
abstract: 'test module for fluentd'
author:
  - 'Shinichiro Sato <s2otsa59@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Fluentd
name: Test-Fluentd
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/S2/p5-Test-fluentd.git
version: 0.01
